Lab7  backend part
o-shelep/chaos-state pull request #6
Opened 2024-10-27 12:56 UTC by o-shelep

2024-10-29 08:13 UTC, Sega-128 requested changes

2024-10-29 08:13 UTC, Sega-128 commented on app/app.js
> +app.use(cors());
ну я б все ж налаштував CORS. 
Подивіться що це і для чого. 
Думаю це не займе багато часу добавити.

2024-10-29 08:13 UTC, Sega-128 commented on app/controllers/authController.js
> +const { promisify } = require("util");
доречі до нативних пакетів ноди, гарною практикою вважається додавати префікс node:

наприклад:
node:util, node:path, node:fs ....


є пакети наприклад в npm ,з назвою fs. Це доречі одна із причин префікса
[fs](https://www.npmjs.com/package/fs)

2024-10-29 08:13 UTC, Sega-128 commented on app/controllers/authController.js
> +  // const user = await User.findOne({ email }, { password: 1 });
о прікольно, я це пам*ятаю що розказував)

2024-10-29 08:13 UTC, Sega-128 commented on app/controllers/testController.js
> +exports.getAllTests = catchAsync(async (req, res) => {
не дуже гарно всі тести витягувати. 

Вам тут не потрібно ніякої пагінації ?

2024-10-29 08:13 UTC, Sega-128 commented on app/controllers/userController.js
> +  const users = await User.find();
точно гарна ідея повертати всіх юзерів. Може пагінацію якусь треба.

2024-10-29 08:13 UTC, Sega-128 commented on app/controllers/userController.js
> +  const userId = req.user._id;
бачу не любите деструктуризацію.Можна і так.

const {_id: userId } = req.user;

2024-10-29 08:13 UTC, Sega-128 commented on app/models/userModel.js
> +      select: false,
о це гарний параметр для пароля

 select: false,

2024-10-29 08:13 UTC, Sega-128 commented on frontend/package.json
> +  "husky": {
це тут лишнє. Це стара конфігурація.
  можете видалити
  "husky": { 
    "hooks": { 	    "hooks": {
      "pre-commit": "lint-staged" 	      "pre-commit": "lint-staged"
    } 	    }

2024-10-29 08:13 UTC, Sega-128 commented on frontend/src/components/Main/Main.jsx
> +    const testId = "66f586bec76785b1bfc0d33b";
const testId = "66f586bec76785b1bfc0d33b";
 
а це що за хардкод і для чого ?

2024-10-29 08:13 UTC, Sega-128 commented on frontend/src/components/Result/Result.jsx
> +        if (!response.ok) {
на бекенді добавили а на фронті захардкодили все. Повиносіть всюди.

http://localhost:5000-> це винесіть десь в змінні середовища.
Тут про змінні середовища в react
[environment react](https://create-react-app.dev/docs/adding-custom-environment-variables/)

Тут про змінні середовища в загальному.

[Best Practices for Bootstrapping a Node.js Application Configuration](https://www.lirantal.com/blog/best-practices-for-bootstrapping-a-node-js-application-configuration)
[Best Practices for Handling Per-Environment Configuration in Your JS/TS Applications](https://www.raulmelo.me/en/blog/best-practices-for-handling-per-environment-config-js-ts-applications)
[Environment variables and configuration anti patterns in Node.js applications](https://www.lirantal.com/blog/environment-variables-configuration-anti-patterns-node-js-applications)

2024-10-29 08:13 UTC, Sega-128 commented on frontend/src/components/Test/Test.jsx
> +                    method: 'GET',
![2024-10-29_09-58](https://github.com/user-attachments/assets/0a9121ce-0006-4ec1-ba15-d15db9fd22da)

Всюди добавлені користувацькі хуки ?


Ще в хуках можна наприклад викликати сервіси або апі. Щоб розділити логіку. Але це за бажанням. Але хуки Обов*язково.

2024-10-29 08:13 UTC, Sega-128 commented on frontend/src/hooks/useAuth.jsx
> +        try {
Дуже багато вкладеностей. Я б це записав так. Але це не значить що потрібно переробити. Просто коли пишете багато вкладеностей, подумайте чи це читаємо.

```
 const result = await signIn(email, password);
            if (!result.token) {
                console.error(result.message);
                return { success: false, error: result.message };
            }

            localStorage.setItem("token", result.token);
            const profileResult = await fetchUsername(email);
            if (profileResult.data && profileResult.data.user) {
                setUsername(profileResult.data.user.name);
                localStorage.setItem("username", profileResult.data.user.name);
                return { success: true };
            } 

            console.error(profileResult.message);
            return { success: false, error: profileResult.message };
```

2024-10-29 08:13 UTC, Sega-128 commented on frontend/src/hooks/usePaginatedTests.jsx
> +            fetchUserData(token).then((data) => {
о у вас в хуках сервіси. Гарно.

Чому всюди так не зробите одинаково ?

Перегляньте хуки і сервіси.

2024-10-29 08:13 UTC, Sega-128 commented on frontend/src/services/authService.js
> +const API_URL = "http://localhost:5000/auth";
тут є API_URL

А нище захардкоджено в  fetchUsername

Приведіть до одного виду. Змінні середовища будь ласка.
І env.example .

2024-10-29 09:58 UTC, o-shelep commented on frontend/src/components/Result/Result.jsx
> +        if (!response.ok) {
винесла в файл .env

2024-10-29 09:59 UTC, o-shelep commented on frontend/src/components/Test/Test.jsx
> +                    method: 'GET',
додала хуки в Test.jsx, Result.jsx, CreateTest.jsx

2024-10-29 09:59 UTC, o-shelep commented on frontend/src/hooks/usePaginatedTests.jsx
> +            fetchUserData(token).then((data) => {
зробила всюди однаково

2024-10-29 10:00 UTC, o-shelep commented on frontend/src/services/authService.js
> +const API_URL = "http://localhost:5000/auth";
привела до одного виду, тепер url дістається з .env

2024-10-30 09:27 UTC, o-shelep commented on frontend/src/components/Main/Main.jsx
> +    const testId = "66f586bec76785b1bfc0d33b";
я додала цей testId в .env

2024-10-30 09:27 UTC, o-shelep commented on app/controllers/authController.js
> +const { promisify } = require("util");
додала до всіх нативних пакетів префікс нод

2024-10-30 09:27 UTC, o-shelep commented on app/app.js
> +app.use(cors());
налаштувала corsOptions

2025-09-21 14:25 UTC, closed without merging